apiVersion: v1
clusters:
- cluster:
    certificate-authority: C:\Users\bigbu\.minikube\ca.crt
    extensions:
    - extension:
        last-update: Thu, 09 Feb 2023 11:04:44 EET
        provider: minikube.sigs.k8s.io
        version: v1.29.0
      name: cluster_info
    server: https://172.23.18.56:8443
  name: dotnetK8s
contexts:
- context:
    cluster: dotnetK8s
    extensions:
    - extension:
        last-update: Thu, 09 Feb 2023 11:04:44 EET
        provider: minikube.sigs.k8s.io
        version: v1.29.0
      name: context_info
    namespace: default
    user: dotnetK8s
  name: dotnetK8s
current-context: dotnetK8s
kind: Config
preferences: {}
users:
- name: dotnetK8s
  user:
    client-certificate: C:\Users\bigbu\.minikube\profiles\dotnetK8s\client.crt
    client-key: C:\Users\bigbu\.minikube\profiles\dotnetK8s\client.key